services:
  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/coursequest
      - AUTO_INGEST=1
      - AUTO_INGEST_PATH=/data/courses.csv
      - REDIS_URL=redis://redis:6379/0   # 👈 backend knows where Redis is
    volumes:
      - ./data/courses.csv:/sample_data/courses.csv
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:8000"
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coursequest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
